apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-api-disk
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: enterprise-multishare-rwx
  resources:
    requests:
      storage: 100Gi  # Supports 10Gi to 1Ti per share # Note: GCP Filestore enterprise/standard instances often require a minimum of 1Ti capacity allocations depending on cluster version
