apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-api-disk
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: filestore-prod-network-sc  # <--- Change this line here!
  resources:
    requests:
      storage: 1Ti  # Or whatever capacity size you had defined
