apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-api-disk
spec:
  accessModes:
    - ReadWriteMany  # Allows both pods to read/write at the same time
  resources:
    requests:
      storage: 1Gi
